name: CI/CD Pipeline to Kubernetes

on:
  push:
    branches: ["master"]

jobs:
  run-tests:
    name: Run Automated Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci # Menjalankan Jest dalam mode non-interaktif

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: run-tests # <-- PENTING: Job ini hanya berjalan jika 'run-tests' sukses

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-k8s-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-k8s-app:${{ github.sha }}

  deploy-to-vps:
    name: Deploy to Kubernetes on VPS
    runs-on: ubuntu-latest
    needs: build-and-push # Job ini berjalan setelah build-and-push sukses

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying to Kubernetes..."
            kubectl apply -f /root/k3s/k8s-deployment-simple.yml
            kubectl set image deployment/nextjs-deployment nextjs-app=${{ secrets.DOCKERHUB_USERNAME }}/nextjs-k8s-app:latest
            kubectl rollout restart deployment/nextjs-deployment
            kubectl rollout status deployment/nextjs-deployment --timeout=300s
            echo "Deployment completed successfully."
