name: CI/CD Pipeline to Kubernetes

on:
  push:
    branches: ["main"] # Memicu workflow saat ada push ke branch main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-k8s-app:latest # Ganti 'nextjs-k8s-app' jika perlu

  deploy-to-vps:
    name: Deploy to Kubernetes on VPS
    needs: build-and-push # Jalankan job ini setelah build-and-push selesai
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Perintah yang akan dijalankan di VPS
            echo "Deploying to Kubernetes..."
            # Perintahkan Kubernetes untuk memperbarui image pada deployment yang ada
            # Pastikan 'nextjs-deployment' sesuai dengan nama deployment Anda di Kubernetes
            kubectl set image deployment/nextjs-deployment nextjs-app=${{ secrets.DOCKERHUB_USERNAME }}/nextjs-k8s-app:latest --record
            echo "Deployment triggered."
